// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmwMrkpTGuDkU0y8pB5p7us8dqMmFaRqg',
    appId: '1:110383945595:web:029f196f1467cc8498cfde',
    messagingSenderId: '110383945595',
    projectId: 'pinterest-clone-8a9be',
    authDomain: 'pinterest-clone-8a9be.firebaseapp.com',
    storageBucket: 'pinterest-clone-8a9be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4uUlk9YJy3ZHksNdETZVktfkGO0DpUO4',
    appId: '1:110383945595:android:f20c2b5a0fea20a398cfde',
    messagingSenderId: '110383945595',
    projectId: 'pinterest-clone-8a9be',
    storageBucket: 'pinterest-clone-8a9be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZXt_1tmY6_W6qDM-VSXPd7hKDDKK3vws',
    appId: '1:110383945595:ios:6d59c69b4910c05d98cfde',
    messagingSenderId: '110383945595',
    projectId: 'pinterest-clone-8a9be',
    storageBucket: 'pinterest-clone-8a9be.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
